(() => {
  "use strict";

  const languages = [
    { id: "en", label: "English 🇺🇸", name: "English", htmlLang: "en", dir: "ltr" },
    { id: "es", label: "Spanish 🇪🇸", name: "Español", htmlLang: "es", dir: "ltr" },
    { id: "zh-CN", label: "Chinese (Simplified) 🇨🇳", name: "简体中文", htmlLang: "zh-CN", dir: "ltr" },
    { id: "ko", label: "Korean 🇰🇷", name: "한국어", htmlLang: "ko", dir: "ltr" },
    { id: "hi", label: "Hindi 🇮🇳", name: "हिन्दी", htmlLang: "hi", dir: "ltr" },
    { id: "vi", label: "Vietnamese 🇻🇳", name: "Tiếng Việt", htmlLang: "vi", dir: "ltr" },
    { id: "ja", label: "Japanese 🇯🇵", name: "日本語", htmlLang: "ja", dir: "ltr" },
    { id: "ar", label: "Arabic 🇸🇦", name: "العربية", htmlLang: "ar", dir: "rtl" },
    { id: "pt-BR", label: "Portuguese 🇧🇷", name: "Português", htmlLang: "pt-BR", dir: "ltr" },
    { id: "fr", label: "French 🇫🇷", name: "Français", htmlLang: "fr", dir: "ltr" },
    { id: "de", label: "German 🇩🇪", name: "Deutsch", htmlLang: "de", dir: "ltr" },
    { id: "ru", label: "Russian 🇷🇺", name: "Русский", htmlLang: "ru", dir: "ltr" },
    { id: "tr", label: "Turkish 🇹🇷", name: "Türkçe", htmlLang: "tr", dir: "ltr" },
    { id: "it", label: "Italian 🇮🇹", name: "Italiano", htmlLang: "it", dir: "ltr" },
    { id: "id", label: "Indonesian 🇮🇩", name: "Bahasa Indonesia", htmlLang: "id", dir: "ltr" },
    { id: "th", label: "Thai 🇹🇭", name: "ไทย", htmlLang: "th", dir: "ltr" },
    { id: "pirate", label: "Pirate English 🏴‍☠️", name: "Pirate English", htmlLang: "en", dir: "ltr", fun: true },
    { id: "medieval", label: "Medieval English ⚔️", name: "Medieval English", htmlLang: "en", dir: "ltr", fun: true },
    { id: "hacker", label: "Hacker Mode 💻", name: "Hacker Mode", htmlLang: "en", dir: "ltr", fun: true },
    { id: "zelda", label: "Zelda Mode 🟡", name: "Zelda Mode", htmlLang: "en", dir: "ltr", fun: true },
    { id: "star-wars", label: "Star Wars Mode 🌌", name: "Star Wars Mode", htmlLang: "en", dir: "ltr", fun: true },
    { id: "dwarf-fortress", label: "Dwarf Fortress Mode ⛏️", name: "Dwarf Fortress Mode", htmlLang: "en", dir: "ltr", fun: true }
  ];

  const dictionaries = {
    es: {
      Roadmap: "Plan de estudios", Course: "Curso", Courses: "Cursos", Search: "Buscar",
      "Search Course Code or Name": "Buscar código o nombre del curso", Spring: "Primavera", Summer: "Verano",
      Fall: "Otoño", credits: "créditos", credit: "crédito", Ready: "Listo", Locked: "Bloqueado",
      Satisfied: "Satisfecho", Completed: "Completado", GPA: "Promedio", Notes: "Notas", Edit: "Editar",
      Save: "Guardar", Cancel: "Cancelar", Delete: "Eliminar", Settings: "Configuración", Semester: "Semestre",
      Current: "Actual", Draft: "Borrador", Drafts: "Borradores", Import: "Importar", Export: "Exportar",
      Reset: "Restablecer", Done: "Listo", Filter: "Filtro", Filters: "Filtros", Sort: "Ordenar",
      Major: "Especialidad", Thread: "Área", Concentration: "Concentración", Requirements: "Requisitos",
      Prerequisite: "Prerrequisito", Prerequisites: "Prerrequisitos", Corequisite: "Correquisito",
      Corequisites: "Correquisitos", Add: "Agregar", Remove: "Quitar", Close: "Cerrar", Zoom: "Zoom",
      "What's New": "Novedades", "Delete Draft": "Eliminar borrador", "Share Your Feedback": "Comparte tus comentarios",
      "Open Feedback Form": "Abrir formulario de comentarios"
    },
    "zh-CN": {
      Roadmap: "路线图", Course: "课程", Courses: "课程", Search: "搜索",
      "Search Course Code or Name": "搜索课程代码或名称", Spring: "春季", Summer: "夏季", Fall: "秋季",
      credits: "学分", credit: "学分", Ready: "可选", Locked: "已锁定", Satisfied: "已满足",
      Completed: "已完成", GPA: "绩点", Notes: "备注", Edit: "编辑", Save: "保存", Cancel: "取消",
      Delete: "删除", Settings: "设置", Semester: "学期", Current: "当前", Draft: "草稿", Drafts: "草稿",
      Import: "导入", Export: "导出", Reset: "重置", Done: "完成", Filter: "筛选", Filters: "筛选",
      Sort: "排序", Major: "专业", Thread: "方向", Concentration: "专攻", Requirements: "要求",
      Prerequisite: "先修课", Prerequisites: "先修课", Corequisite: "共修课", Corequisites: "共修课",
      Add: "添加", Remove: "移除", Close: "关闭", Zoom: "缩放", "What's New": "新增内容",
      "Delete Draft": "删除草稿", "Share Your Feedback": "分享反馈", "Open Feedback Form": "打开反馈表"
    },
    ko: {
      Roadmap: "로드맵", Course: "강좌", Courses: "강좌", Search: "검색",
      "Search Course Code or Name": "강좌 코드 또는 이름 검색", Spring: "봄", Summer: "여름", Fall: "가을",
      credits: "학점", credit: "학점", Ready: "준비됨", Locked: "잠김", Satisfied: "충족됨",
      Completed: "완료됨", GPA: "평점", Notes: "메모", Edit: "편집", Save: "저장", Cancel: "취소",
      Delete: "삭제", Settings: "설정", Semester: "학기", Current: "현재", Draft: "초안", Drafts: "초안",
      Import: "가져오기", Export: "내보내기", Reset: "재설정", Done: "완료", Filter: "필터", Filters: "필터",
      Sort: "정렬", Major: "전공", Thread: "스레드", Concentration: "집중 분야", Requirements: "요건",
      Prerequisite: "선수 과목", Prerequisites: "선수 과목", Corequisite: "동시 이수 과목",
      Corequisites: "동시 이수 과목", Add: "추가", Remove: "제거", Close: "닫기", Zoom: "확대/축소",
      "What's New": "새로운 기능", "Delete Draft": "초안 삭제", "Share Your Feedback": "피드백 공유",
      "Open Feedback Form": "피드백 양식 열기"
    },
    hi: {
      Roadmap: "रोडमैप", Course: "पाठ्यक्रम", Courses: "पाठ्यक्रम", Search: "खोजें",
      "Search Course Code or Name": "कोर्स कोड या नाम खोजें", Spring: "वसंत", Summer: "ग्रीष्म",
      Fall: "पतझड़", credits: "क्रेडिट", credit: "क्रेडिट", Ready: "तैयार", Locked: "लॉक",
      Satisfied: "पूर्ण", Completed: "पूर्ण", GPA: "जीपीए", Notes: "नोट्स", Edit: "संपादित करें",
      Save: "सहेजें", Cancel: "रद्द करें", Delete: "हटाएँ", Settings: "सेटिंग्स", Semester: "सेमेस्टर",
      Current: "वर्तमान", Draft: "ड्राफ्ट", Drafts: "ड्राफ्ट", Import: "आयात", Export: "निर्यात",
      Reset: "रीसेट", Done: "हो गया", Filter: "फ़िल्टर", Filters: "फ़िल्टर", Sort: "क्रमबद्ध करें",
      Major: "मुख्य विषय", Thread: "थ्रेड", Concentration: "एकाग्रता", Requirements: "आवश्यकताएँ",
      Prerequisite: "पूर्वापेक्षा", Prerequisites: "पूर्वापेक्षाएँ", Corequisite: "सह-आवश्यकता",
      Corequisites: "सह-आवश्यकताएँ", Add: "जोड़ें", Remove: "हटाएँ", Close: "बंद करें", Zoom: "ज़ूम",
      "What's New": "नया क्या है", "Delete Draft": "ड्राफ्ट हटाएँ", "Share Your Feedback": "प्रतिक्रिया साझा करें",
      "Open Feedback Form": "प्रतिक्रिया फ़ॉर्म खोलें"
    },
    vi: {
      Roadmap: "Lộ trình", Course: "Khóa học", Courses: "Khóa học", Search: "Tìm kiếm",
      "Search Course Code or Name": "Tìm mã hoặc tên khóa học", Spring: "Mùa xuân", Summer: "Mùa hè",
      Fall: "Mùa thu", credits: "tín chỉ", credit: "tín chỉ", Ready: "Sẵn sàng", Locked: "Đã khóa",
      Satisfied: "Đã thỏa mãn", Completed: "Đã hoàn thành", GPA: "GPA", Notes: "Ghi chú", Edit: "Sửa",
      Save: "Lưu", Cancel: "Hủy", Delete: "Xóa", Settings: "Cài đặt", Semester: "Học kỳ",
      Current: "Hiện tại", Draft: "Bản nháp", Drafts: "Bản nháp", Import: "Nhập", Export: "Xuất",
      Reset: "Đặt lại", Done: "Xong", Filter: "Bộ lọc", Filters: "Bộ lọc", Sort: "Sắp xếp",
      Major: "Ngành", Thread: "Luồng", Concentration: "Chuyên ngành", Requirements: "Yêu cầu",
      Prerequisite: "Điều kiện tiên quyết", Prerequisites: "Điều kiện tiên quyết", Corequisite: "Điều kiện đồng thời",
      Corequisites: "Điều kiện đồng thời", Add: "Thêm", Remove: "Xóa", Close: "Đóng", Zoom: "Thu phóng",
      "What's New": "Có gì mới", "Delete Draft": "Xóa bản nháp", "Share Your Feedback": "Chia sẻ phản hồi",
      "Open Feedback Form": "Mở biểu mẫu phản hồi"
    },
    ja: {
      Roadmap: "ロードマップ", Course: "科目", Courses: "科目", Search: "検索",
      "Search Course Code or Name": "科目コードまたは名前を検索", Spring: "春", Summer: "夏", Fall: "秋",
      credits: "単位", credit: "単位", Ready: "履修可", Locked: "ロック中", Satisfied: "満たしています",
      Completed: "完了", GPA: "GPA", Notes: "メモ", Edit: "編集", Save: "保存", Cancel: "キャンセル",
      Delete: "削除", Settings: "設定", Semester: "学期", Current: "現在", Draft: "下書き", Drafts: "下書き",
      Import: "インポート", Export: "エクスポート", Reset: "リセット", Done: "完了", Filter: "フィルター",
      Filters: "フィルター", Sort: "並べ替え", Major: "専攻", Thread: "スレッド", Concentration: "集中分野",
      Requirements: "要件", Prerequisite: "前提条件", Prerequisites: "前提条件", Corequisite: "同時履修条件",
      Corequisites: "同時履修条件", Add: "追加", Remove: "削除", Close: "閉じる", Zoom: "ズーム",
      "What's New": "新機能", "Delete Draft": "下書きを削除", "Share Your Feedback": "フィードバックを共有",
      "Open Feedback Form": "フィードバックフォームを開く"
    },
    ar: {
      Roadmap: "خريطة الطريق", Course: "مقرر", Courses: "المقررات", Search: "بحث",
      "Search Course Code or Name": "ابحث برمز المقرر أو اسمه", Spring: "الربيع", Summer: "الصيف",
      Fall: "الخريف", credits: "ساعات", credit: "ساعة", Ready: "جاهز", Locked: "مغلق",
      Satisfied: "مستوفى", Completed: "مكتمل", GPA: "المعدل", Notes: "ملاحظات", Edit: "تعديل",
      Save: "حفظ", Cancel: "إلغاء", Delete: "حذف", Settings: "الإعدادات", Semester: "الفصل",
      Current: "الحالي", Draft: "مسودة", Drafts: "مسودات", Import: "استيراد", Export: "تصدير",
      Reset: "إعادة ضبط", Done: "تم", Filter: "تصفية", Filters: "مرشحات", Sort: "ترتيب",
      Major: "التخصص", Thread: "المسار", Concentration: "التركيز", Requirements: "المتطلبات",
      Prerequisite: "متطلب سابق", Prerequisites: "متطلبات سابقة", Corequisite: "متطلب متزامن",
      Corequisites: "متطلبات متزامنة", Add: "إضافة", Remove: "إزالة", Close: "إغلاق", Zoom: "تكبير",
      "What's New": "ما الجديد", "Delete Draft": "حذف المسودة", "Share Your Feedback": "شارك ملاحظاتك",
      "Open Feedback Form": "فتح نموذج الملاحظات"
    },
    "pt-BR": {
      Roadmap: "Roteiro", Course: "Curso", Courses: "Cursos", Search: "Pesquisar",
      "Search Course Code or Name": "Pesquisar código ou nome do curso", Spring: "Primavera", Summer: "Verão",
      Fall: "Outono", credits: "créditos", credit: "crédito", Ready: "Pronto", Locked: "Bloqueado",
      Satisfied: "Satisfeito", Completed: "Concluído", GPA: "Média", Notes: "Notas", Edit: "Editar",
      Save: "Salvar", Cancel: "Cancelar", Delete: "Excluir", Settings: "Configurações", Semester: "Semestre",
      Current: "Atual", Draft: "Rascunho", Drafts: "Rascunhos", Import: "Importar", Export: "Exportar",
      Reset: "Redefinir", Done: "Concluído", Filter: "Filtro", Filters: "Filtros", Sort: "Ordenar",
      Major: "Curso principal", Thread: "Trilha", Concentration: "Concentração", Requirements: "Requisitos",
      Prerequisite: "Pré-requisito", Prerequisites: "Pré-requisitos", Corequisite: "Co-requisito",
      Corequisites: "Co-requisitos", Add: "Adicionar", Remove: "Remover", Close: "Fechar", Zoom: "Zoom",
      "What's New": "Novidades", "Delete Draft": "Excluir rascunho", "Share Your Feedback": "Compartilhe seu feedback",
      "Open Feedback Form": "Abrir formulário de feedback"
    },
    fr: {
      Roadmap: "Parcours", Course: "Cours", Courses: "Cours", Search: "Rechercher",
      "Search Course Code or Name": "Rechercher un code ou nom de cours", Spring: "Printemps", Summer: "Été",
      Fall: "Automne", credits: "crédits", credit: "crédit", Ready: "Prêt", Locked: "Verrouillé",
      Satisfied: "Satisfait", Completed: "Terminé", GPA: "Moyenne", Notes: "Notes", Edit: "Modifier",
      Save: "Enregistrer", Cancel: "Annuler", Delete: "Supprimer", Settings: "Paramètres", Semester: "Semestre",
      Current: "Actuel", Draft: "Brouillon", Drafts: "Brouillons", Import: "Importer", Export: "Exporter",
      Reset: "Réinitialiser", Done: "Terminé", Filter: "Filtre", Filters: "Filtres", Sort: "Trier",
      Major: "Majeure", Thread: "Parcours", Concentration: "Concentration", Requirements: "Exigences",
      Prerequisite: "Prérequis", Prerequisites: "Prérequis", Corequisite: "Corequis", Corequisites: "Corequis",
      Add: "Ajouter", Remove: "Retirer", Close: "Fermer", Zoom: "Zoom", "What's New": "Nouveautés",
      "Delete Draft": "Supprimer le brouillon", "Share Your Feedback": "Partager vos commentaires",
      "Open Feedback Form": "Ouvrir le formulaire de commentaires"
    },
    de: {
      Roadmap: "Studienplan", Course: "Kurs", Courses: "Kurse", Search: "Suchen",
      "Search Course Code or Name": "Kurscode oder Namen suchen", Spring: "Frühling", Summer: "Sommer",
      Fall: "Herbst", credits: "Credits", credit: "Credit", Ready: "Bereit", Locked: "Gesperrt",
      Satisfied: "Erfüllt", Completed: "Abgeschlossen", GPA: "Notenschnitt", Notes: "Notizen", Edit: "Bearbeiten",
      Save: "Speichern", Cancel: "Abbrechen", Delete: "Löschen", Settings: "Einstellungen", Semester: "Semester",
      Current: "Aktuell", Draft: "Entwurf", Drafts: "Entwürfe", Import: "Importieren", Export: "Exportieren",
      Reset: "Zurücksetzen", Done: "Fertig", Filter: "Filter", Filters: "Filter", Sort: "Sortieren",
      Major: "Hauptfach", Thread: "Schwerpunkt", Concentration: "Vertiefung", Requirements: "Anforderungen",
      Prerequisite: "Voraussetzung", Prerequisites: "Voraussetzungen", Corequisite: "Gleichzeitige Voraussetzung",
      Corequisites: "Gleichzeitige Voraussetzungen", Add: "Hinzufügen", Remove: "Entfernen", Close: "Schließen",
      Zoom: "Zoom", "What's New": "Neuigkeiten", "Delete Draft": "Entwurf löschen",
      "Share Your Feedback": "Feedback teilen", "Open Feedback Form": "Feedbackformular öffnen"
    },
    ru: {
      Roadmap: "План", Course: "Курс", Courses: "Курсы", Search: "Поиск",
      "Search Course Code or Name": "Поиск по коду или названию курса", Spring: "Весна", Summer: "Лето",
      Fall: "Осень", credits: "кредита", credit: "кредит", Ready: "Готово", Locked: "Заблокировано",
      Satisfied: "Выполнено", Completed: "Завершено", GPA: "GPA", Notes: "Заметки", Edit: "Изменить",
      Save: "Сохранить", Cancel: "Отмена", Delete: "Удалить", Settings: "Настройки", Semester: "Семестр",
      Current: "Текущий", Draft: "Черновик", Drafts: "Черновики", Import: "Импорт", Export: "Экспорт",
      Reset: "Сброс", Done: "Готово", Filter: "Фильтр", Filters: "Фильтры", Sort: "Сортировать",
      Major: "Специальность", Thread: "Направление", Concentration: "Концентрация", Requirements: "Требования",
      Prerequisite: "Пререквизит", Prerequisites: "Пререквизиты", Corequisite: "Кореквизит",
      Corequisites: "Кореквизиты", Add: "Добавить", Remove: "Удалить", Close: "Закрыть", Zoom: "Масштаб",
      "What's New": "Что нового", "Delete Draft": "Удалить черновик", "Share Your Feedback": "Оставить отзыв",
      "Open Feedback Form": "Открыть форму отзыва"
    },
    tr: {
      Roadmap: "Yol haritası", Course: "Ders", Courses: "Dersler", Search: "Ara",
      "Search Course Code or Name": "Ders kodu veya adı ara", Spring: "İlkbahar", Summer: "Yaz", Fall: "Güz",
      credits: "kredi", credit: "kredi", Ready: "Hazır", Locked: "Kilitli", Satisfied: "Karşılandı",
      Completed: "Tamamlandı", GPA: "GPA", Notes: "Notlar", Edit: "Düzenle", Save: "Kaydet",
      Cancel: "İptal", Delete: "Sil", Settings: "Ayarlar", Semester: "Dönem", Current: "Geçerli",
      Draft: "Taslak", Drafts: "Taslaklar", Import: "İçe aktar", Export: "Dışa aktar", Reset: "Sıfırla",
      Done: "Bitti", Filter: "Filtre", Filters: "Filtreler", Sort: "Sırala", Major: "Ana dal",
      Thread: "Alan", Concentration: "Yoğunlaşma", Requirements: "Gereksinimler", Prerequisite: "Ön koşul",
      Prerequisites: "Ön koşullar", Corequisite: "Eş koşul", Corequisites: "Eş koşullar", Add: "Ekle",
      Remove: "Kaldır", Close: "Kapat", Zoom: "Yakınlaştır", "What's New": "Yenilikler",
      "Delete Draft": "Taslağı sil", "Share Your Feedback": "Geri bildiriminizi paylaşın",
      "Open Feedback Form": "Geri bildirim formunu aç"
    },
    it: {
      Roadmap: "Percorso", Course: "Corso", Courses: "Corsi", Search: "Cerca",
      "Search Course Code or Name": "Cerca codice o nome del corso", Spring: "Primavera", Summer: "Estate",
      Fall: "Autunno", credits: "crediti", credit: "credito", Ready: "Pronto", Locked: "Bloccato",
      Satisfied: "Soddisfatto", Completed: "Completato", GPA: "Media", Notes: "Note", Edit: "Modifica",
      Save: "Salva", Cancel: "Annulla", Delete: "Elimina", Settings: "Impostazioni", Semester: "Semestre",
      Current: "Corrente", Draft: "Bozza", Drafts: "Bozze", Import: "Importa", Export: "Esporta",
      Reset: "Reimposta", Done: "Fatto", Filter: "Filtro", Filters: "Filtri", Sort: "Ordina",
      Major: "Corso principale", Thread: "Percorso", Concentration: "Concentrazione", Requirements: "Requisiti",
      Prerequisite: "Prerequisito", Prerequisites: "Prerequisiti", Corequisite: "Corequisito",
      Corequisites: "Corequisiti", Add: "Aggiungi", Remove: "Rimuovi", Close: "Chiudi", Zoom: "Zoom",
      "What's New": "Novità", "Delete Draft": "Elimina bozza", "Share Your Feedback": "Condividi feedback",
      "Open Feedback Form": "Apri modulo feedback"
    },
    id: {
      Roadmap: "Peta jalan", Course: "Mata kuliah", Courses: "Mata kuliah", Search: "Cari",
      "Search Course Code or Name": "Cari kode atau nama mata kuliah", Spring: "Musim semi", Summer: "Musim panas",
      Fall: "Musim gugur", credits: "kredit", credit: "kredit", Ready: "Siap", Locked: "Terkunci",
      Satisfied: "Terpenuhi", Completed: "Selesai", GPA: "IPK", Notes: "Catatan", Edit: "Edit",
      Save: "Simpan", Cancel: "Batal", Delete: "Hapus", Settings: "Pengaturan", Semester: "Semester",
      Current: "Saat ini", Draft: "Draf", Drafts: "Draf", Import: "Impor", Export: "Ekspor",
      Reset: "Atur ulang", Done: "Selesai", Filter: "Filter", Filters: "Filter", Sort: "Urutkan",
      Major: "Jurusan", Thread: "Jalur", Concentration: "Konsentrasi", Requirements: "Persyaratan",
      Prerequisite: "Prasyarat", Prerequisites: "Prasyarat", Corequisite: "Koprasyarat", Corequisites: "Koprasyarat",
      Add: "Tambah", Remove: "Hapus", Close: "Tutup", Zoom: "Zoom", "What's New": "Yang baru",
      "Delete Draft": "Hapus draf", "Share Your Feedback": "Bagikan masukan", "Open Feedback Form": "Buka formulir masukan"
    },
    th: {
      Roadmap: "แผนการเรียน", Course: "รายวิชา", Courses: "รายวิชา", Search: "ค้นหา",
      "Search Course Code or Name": "ค้นหารหัสหรือชื่อรายวิชา", Spring: "ฤดูใบไม้ผลิ", Summer: "ฤดูร้อน",
      Fall: "ฤดูใบไม้ร่วง", credits: "หน่วยกิต", credit: "หน่วยกิต", Ready: "พร้อม", Locked: "ล็อก",
      Satisfied: "ผ่านเงื่อนไข", Completed: "เสร็จสิ้น", GPA: "GPA", Notes: "บันทึก", Edit: "แก้ไข",
      Save: "บันทึก", Cancel: "ยกเลิก", Delete: "ลบ", Settings: "การตั้งค่า", Semester: "ภาคเรียน",
      Current: "ปัจจุบัน", Draft: "แบบร่าง", Drafts: "แบบร่าง", Import: "นำเข้า", Export: "ส่งออก",
      Reset: "รีเซ็ต", Done: "เสร็จ", Filter: "ตัวกรอง", Filters: "ตัวกรอง", Sort: "เรียงลำดับ",
      Major: "สาขา", Thread: "สายวิชา", Concentration: "ความเข้มข้น", Requirements: "ข้อกำหนด",
      Prerequisite: "วิชาบังคับก่อน", Prerequisites: "วิชาบังคับก่อน", Corequisite: "วิชาที่เรียนร่วม",
      Corequisites: "วิชาที่เรียนร่วม", Add: "เพิ่ม", Remove: "นำออก", Close: "ปิด", Zoom: "ซูม",
      "What's New": "มีอะไรใหม่", "Delete Draft": "ลบแบบร่าง", "Share Your Feedback": "แชร์ความคิดเห็น",
      "Open Feedback Form": "เปิดแบบฟอร์มความคิดเห็น"
    },
    pirate: {
      Roadmap: "Treasure Map", Course: "Lesson o' the Sea", Courses: "Lessons o' the Sea", Search: "Scour",
      "Search Course Code or Name": "Scour fer Course Code or Name", Spring: "Spring Tide", Summer: "Sunlit Voyage",
      Fall: "Autumn Voyage", credits: "doubloons", credit: "doubloon", Ready: "Ready to Sail", Locked: "Locked in the Brig",
      Satisfied: "Treasure Claimed", Completed: "Voyage Complete", "Course Completed": "Voyage Complete",
      "Prerequisite Missing": "Ye Lack the Required Knowledge", GPA: "Captain's Mark", Notes: "Captain's Log",
      Edit: "Revise the Chart", Save: "Stow It", Cancel: "Belay That", Delete: "Send to the Deep",
      Settings: "Ship Settings", Semester: "Voyage", Current: "Current", Draft: "Chart Draft", Drafts: "Chart Drafts",
      Import: "Bring Aboard", Export: "Send Ashore", Reset: "Reset the Compass", Done: "Aye", Filter: "Spyglass",
      Filters: "Spyglasses", Sort: "Arrange the Deck", Major: "Main Quest", Thread: "Sea Route",
      Concentration: "Specialty", Requirements: "Orders", Prerequisite: "Required Knowledge",
      Prerequisites: "Required Knowledge", Corequisite: "Sailing Mate", Corequisites: "Sailing Mates",
      Add: "Add Aboard", Remove: "Cast Off", Close: "Batten Down", Zoom: "Spyglass Zoom",
      "Degree Progress": "Treasure Hunt Progress", "Graduation Progress": "Final Voyage Progress",
      "Credits Remaining": "Doubloons Remaining", "Schedule Conflict": "Storm on the Course"
    },
    medieval: {
      Roadmap: "Quest Map", Course: "Lesson", Courses: "Lessons", Search: "Seek",
      "Search Course Code or Name": "Seek Lesson Code or Name", Spring: "Springtide", Summer: "Summertide",
      Fall: "Harvesttide", credits: "honors", credit: "honor", Ready: "Prepared", Locked: "Sealed",
      Satisfied: "Fulfilled", Completed: "Accomplished", "Course Completed": "Knowledge Acquired",
      "Prerequisite Missing": "Required Lore Not Yet Learned", GPA: "Scholarly Standing", Notes: "Scribe Notes",
      Edit: "Amend", Save: "Inscribe", Cancel: "Withdraw", Delete: "Banish", Settings: "Chamber Settings",
      Semester: "Term", Current: "Present", Draft: "Parchment", Drafts: "Parchments", Import: "Summon",
      Export: "Dispatch", Reset: "Restore", Done: "Complete", Filter: "Sieve", Filters: "Sieves",
      Sort: "Order", Major: "Great Calling", Thread: "Path", Concentration: "Discipline",
      Requirements: "Decrees", Prerequisite: "Required Lore", Prerequisites: "Required Lore",
      Corequisite: "Companion Lesson", Corequisites: "Companion Lessons", Add: "Add", Remove: "Remove",
      Close: "Close", Zoom: "Magnify", "Degree Progress": "Quest Progress",
      "Graduation Progress": "Knighthood Progress", "Credits Remaining": "Honors Remaining",
      "Schedule Conflict": "Clashing Obligations"
    },
    hacker: {
      Roadmap: "Execution Plan", Course: "Module", Courses: "Modules", Search: "Query",
      "Search Course Code or Name": "Query Module Code or Name", Spring: "Spring Build", Summer: "Summer Build",
      Fall: "Fall Build", credits: "units", credit: "unit", Ready: "Runnable", Locked: "Access Denied",
      Satisfied: "Resolved", Completed: "Compiled", "Course Completed": "Module Compiled",
      "Prerequisite Missing": "Dependency Missing", GPA: "Performance Index", Notes: "Logs", Edit: "Patch",
      Save: "Commit", Cancel: "Abort", Delete: "Remove", Settings: "Config", Semester: "Build",
      Current: "Current", Draft: "Branch", Drafts: "Branches", Import: "Import", Export: "Export",
      Reset: "Reset", Done: "Done", Filter: "Filter", Filters: "Filters", Sort: "Sort", Major: "Main Process",
      Thread: "Thread", Concentration: "Subsystem", Requirements: "Dependencies", Prerequisite: "Dependency",
      Prerequisites: "Dependencies", Corequisite: "Linked Dependency", Corequisites: "Linked Dependencies",
      Add: "Add", Remove: "Remove", Close: "Close", Zoom: "Scale", "Degree Progress": "Compilation Status",
      "Graduation Progress": "Deployment Progress", "Credits Remaining": "Units Remaining",
      "Schedule Conflict": "Merge Conflict"
    },
    zelda: {
      Roadmap: "Adventure Map", Course: "Trial", Courses: "Trials", Search: "Seek",
      "Search Course Code or Name": "Seek Trial Code or Name", Spring: "Spring Realm", Summer: "Summer Realm",
      Fall: "Autumn Realm", credits: "spirit orbs", credit: "spirit orb", Ready: "Ready", Locked: "Sealed",
      Satisfied: "Blessing Earned", Completed: "Trial Cleared", "Course Completed": "Trial Cleared",
      "Prerequisite Missing": "Sacred Trial Missing", GPA: "Hero's Standing", Notes: "Sheikah Slate Notes",
      Edit: "Adjust", Save: "Save", Cancel: "Cancel", Delete: "Discard", Settings: "Rune Settings",
      Semester: "Realm", Current: "Current", Draft: "Quest Draft", Drafts: "Quest Drafts", Import: "Receive",
      Export: "Send", Reset: "Restore", Done: "Done", Filter: "Lens", Filters: "Lenses", Sort: "Arrange",
      Major: "Hero's Path", Thread: "Questline", Concentration: "Sacred Focus", Requirements: "Trials Required",
      Prerequisite: "Required Trial", Prerequisites: "Required Trials", Corequisite: "Companion Trial",
      Corequisites: "Companion Trials", Add: "Add", Remove: "Remove", Close: "Close", Zoom: "Sheikah Zoom",
      "Degree Progress": "Hero's Journey", "Graduation Progress": "Champion Progress",
      "Credits Remaining": "Spirit Orbs Remaining", "Schedule Conflict": "Blood Moon Scheduling"
    },
    "star-wars": {
      Roadmap: "Star Chart", Course: "Training", Courses: "Trainings", Search: "Scan",
      "Search Course Code or Name": "Scan Training Code or Name", Spring: "Spring Cycle", Summer: "Summer Cycle",
      Fall: "Fall Cycle", credits: "kyber shards", credit: "kyber shard", Ready: "The Force Allows It",
      Locked: "Blocked by the Dark Side", Satisfied: "Balance Achieved", Completed: "Training Complete",
      "Course Completed": "Training Complete", "Prerequisite Missing": "Training Path Incomplete",
      GPA: "Council Standing", Notes: "Holocron Notes", Edit: "Adjust", Save: "Transmit", Cancel: "Abort",
      Delete: "Erase", Settings: "Droid Settings", Semester: "Cycle", Current: "Current", Draft: "Holoplan",
      Drafts: "Holoplans", Import: "Receive", Export: "Transmit", Reset: "Reset", Done: "Done",
      Filter: "Scanner", Filters: "Scanners", Sort: "Order", Major: "Jedi Path", Thread: "Force Path",
      Concentration: "Discipline", Requirements: "Council Requirements", Prerequisite: "Required Training",
      Prerequisites: "Required Trainings", Corequisite: "Paired Training", Corequisites: "Paired Trainings",
      Add: "Add", Remove: "Remove", Close: "Close", Zoom: "Focus", "Degree Progress": "Training Status",
      "Graduation Progress": "Jedi Training Progress", "Credits Remaining": "Kyber Shards Remaining",
      "Schedule Conflict": "Disturbance in the Schedule"
    },
    "dwarf-fortress": {
      Roadmap: "Fortress Plan", Course: "Labor", Courses: "Labors", Search: "Inspect",
      "Search Course Code or Name": "Inspect Labor Code or Name", Spring: "Spring", Summer: "Summer",
      Fall: "Autumn", credits: "work orders", credit: "work order", Ready: "Available", Locked: "Forbidden",
      Satisfied: "Mandate Satisfied", Completed: "Labor Complete", "Course Completed": "Labor Complete",
      "Prerequisite Missing": "Missing Required Craft", GPA: "Fortress Record", Notes: "Engraved Notes",
      Edit: "Designate", Save: "Commit to Stone", Cancel: "Cancel Order", Delete: "Dump", Settings: "Fortress Settings",
      Semester: "Season", Current: "Current", Draft: "Blueprint", Drafts: "Blueprints", Import: "Import",
      Export: "Export", Reset: "Rebuild", Done: "Done", Filter: "Burrow Filter", Filters: "Burrow Filters",
      Sort: "Sort Stockpile", Major: "Noble Mandate", Thread: "Mine Shaft", Concentration: "Workshop Focus",
      Requirements: "Mandates", Prerequisite: "Required Craft", Prerequisites: "Required Crafts",
      Corequisite: "Linked Labor", Corequisites: "Linked Labors", Add: "Add", Remove: "Remove", Close: "Close",
      Zoom: "Inspect", "Degree Progress": "Fortress Progress", "Graduation Progress": "Mountainhome Progress",
      "Credits Remaining": "Work Orders Remaining", "Schedule Conflict": "Catastrophic Planning Event"
    }
  };

  globalThis.GT_ROADMAP_LANGUAGES = languages;
  globalThis.GT_ROADMAP_FUN_LANGUAGE_IDS = languages.filter((language) => language.fun).map((language) => language.id);
  globalThis.GT_ROADMAP_TRANSLATIONS = dictionaries;
})();
